version: "2.4"

services:
  loges01:
    image: opensearchproject/opensearch:latest
    restart: always
    container_name: loges01
    mem_limit: 1024m
    environment:
      - node.name=loges01
      - cluster.name=es-docker-cluster
      - network.host=0.0.0.0
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms384m -Xmx384m"
      # - DISABLE_SECURITY_PLUGIN=true # Disable in production environment
    ports:
      - 9200:9200
      - 9600:9600 # required for Performance Analyzer
    volumes:
      - esdata01:/usr/share/opensearch/data

  logstash:
    build: ./logstash
    restart: always
    container_name: logstash 
    # parametro disponible en compose 2.4
    mem_limit: 512m
    depends_on:
      - loges01
    ports:
      - 5960:5960/udp

  kibana:
    image: opensearchproject/opensearch-dashboards:latest
    restart: always
    container_name: kibana
    environment:
      OPENSEARCH_HOSTS: "https://loges01:9200"
    # parametro disponible en compose 2.4
    mem_limit: 256m
    depends_on:
      - loges01
      - logstash
    ports:
      - 5601:5601
    expose:
      - "5601"
volumes:
  esdata01:
    driver: local